In [88]:
%pip install torch numpy

Note: you may need to restart the kernel to use updated packages.


In [89]:
import torch
import numpy as np

In [90]:
my_list = [30, 20, 10, 40]

In [91]:
new_list = torch.tensor(my_list).reshape(2, 2)
new_list

tensor([[30, 20],
        [10, 40]])

In [92]:
a = torch.tensor([[-2, 1], [1, 3]])
r = torch.randn(2, 2)
ans = 2 * a + r
ans

tensor([[-3.4005,  0.8959],
        [ 2.2246,  5.8702]])

In [93]:
slide_a = ans[:, 0]
slide_b = ans[:, 1]

ans = torch.cat((slide_a, slide_b), dim=0)
ans = ans.unsqueeze(1)
ans

tensor([[-3.4005],
        [ 2.2246],
        [ 0.8959],
        [ 5.8702]])

In [110]:
min_ans = ans.min()
max_ans = ans.max()
c = min_ans * max_ans
c

tensor(-19.9616)

In [111]:

# concat = torch.cat((ans_t[0,0], ans_t[1,0], c), dim=0)
# concat

In [ ]:
ans_t = ans.flatten()

ans_t
first =ans_t[0:2]
last = ans_t[2:4]

c = c.reshape((1))
concat = torch.concat((first,c,last,c), dim=0)
concat

RuntimeError: Tensors must have same number of dimensions: got 1 and 2