In [1]:
!pip install numpy

  Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)


In [4]:
import numpy as np

In [5]:
my_list = [3,2,1,4]
arr = np.array(my_list)

In [8]:
reshaped = arr.reshape(2,2)
reshaped

array([[3, 2],
       [1, 4]])

In [11]:
arr = np.array([[-2, 1], [1, 3]]) * 2
random_arr = np.random.rand(2,2)

problem_2 = arr - random_arr
problem_2

array([[-4.83404327,  1.33611484],
       [ 1.73495193,  5.13091528]])

In [15]:
slide_arr = problem_2[0,:]

output_3 = np.concatenate([slide_arr, slide_arr])
output_3

array([-4.83404327,  1.33611484, -4.83404327,  1.33611484])

In [18]:
max_value = np.max(output_3)
min_v = np.min(output_3)

output_4 = max_value * min_v
output_4

np.float64(-6.458836945539572)

In [ ]:
append_arr = np.append(output_3, output_4)

col_vector_expand = np.expand_dims(append_arr, axis=1)

col_vector_expand

array([[-4.83404327],
       [ 1.33611484],
       [-4.83404327],
       [ 1.33611484],
       [-6.45883695]])